#!/bin/bash
# Uses ffmpeg to limit file size of a video to 8MB for Discord uploads.
iFS=$'\n'
# TODO: Figure out audio bitrate, it is fixed at 128kbps for now

VIDEO_PATH=$1
FILENAME=$(basename $VIDEO_PATH)
OUTPUT=~/Videos/8mb/$FILENAME

VIDEO_LENGTH=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $VIDEO_PATH)
TOTAL_BITRATE=$(expr 64000 / $VIDEO_LENGTH)
VIDEO_BITRATE=$(expr $TOTAL_BITRATE - 128)

ffmpeg -y -i $VIDEO_PATH -c:v libx264 -b:v ${VIDEO_BITRATE}k -pass 1 -f null /dev/null && \
ffmpeg -i $VIDEO_PATH -c:v libx264 -b:v ${VIDEO_BITRATE}k -pass 2 -c:a aac -b:a 128k $OUTPUT
