#!/bin/bash
# Uses ffmpeg to limit file size of a video to 8MB for Discord uploads.
iFS=$'\n'
# TODO: Figure out audio bitrate, it is fixed at 128kbps for now

MAX_FILE_SIZE=8 #mb

VIDEO_PATH=$1
FILENAME=$(basename $VIDEO_PATH)
OUTPUT=~/Videos/8mb/$FILENAME
AUDIO_BITRATE=128


VIDEO_LENGTH=$(ffprobe -i $VIDEO_PATH -show_entries format=duration -v quiet -of csv="p=0" | awk '{printf int($1)}')
VIDEO_SIZE=$(stat -c%s $VIDEO_PATH)
TOTAL_BITRATE=$(($MAX_FILE_SIZE*8000/$VIDEO_LENGTH))
if (( $TOTAL_BITRATE < $AUDIO_BITRATE )); then
    echo "video too thicc cannot compress"
    exit 1
fi
VIDEO_BITRATE=$(expr $TOTAL_BITRATE - $AUDIO_BITRATE)

if (( $VIDEO_SIZE < 8000000 )); then
    echo "why are you doing this, your video is already smol enough"
    exit 1
fi
ffmpeg -y -i $VIDEO_PATH -c:v libx264 -b:v ${VIDEO_BITRATE}k -minrate ${VIDEO_BITRATE}k -maxrate ${VIDEO_BITRATE}k -bufsize 128k -pass 1 -f null /dev/null && \
ffmpeg -i $VIDEO_PATH -c:v libx264 -b:v ${VIDEO_BITRATE}k -minrate ${VIDEO_BITRATE}k -maxrate ${VIDEO_BITRATE}k -bufsize 128k -pass 2 -c:a aac -b:a ${AUDIO_BITRATE}k $OUTPUT
