#!/bin/bash

BATTERY=$(ideviceinfo -q com.apple.mobile.battery -k BatteryCurrentCapacity)
IS_CHARGING=$(ideviceinfo -q com.apple.mobile.battery -k BatteryIsCharging)

if [ "$BATTERY" = "ERROR: No device found!" ]
then
    echo "not connected"
elif [ "$IS_CHARGING" = "false" ]
then
    echo $BATTERY "%" | sed 's/ //g'
else 
    echo $BATTERY "%" | sed 's/ //g'
fi
