#!/bin/bash

BATTERY=$(ideviceinfo -q com.apple.mobile.battery -k BatteryCurrentCapacity)

if [ "$BATTERY" = "ERROR: No device found!" ]
then
    echo "not connected"
else
    echo $BATTERY "%" | sed 's/ //g'
fi
